## HA-2 

#left 105
#right 106
#up 103
#down 108
#
#red 59
#green 60
#yellow 61
#blue 62
#
#
#zoom+ 13 --> play
#zoomlevel1 2--> pause
#zoomlevel2 3 --> forward
#zoomlevel3 4 --> backward
#zoomnormal 11  --> stop (media_player.media_stop)
#
#
#
#


- alias: find out Key codes
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
  action:
  - service: input_text.set_value
    data_template:
      entity_id: input_text.mykeycode
      value: '{{ trigger.event.data.key_code }}'


- alias: script.music_box_next_track
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
      key_code: 106       
  action:
  - service: rest_command.ha_script
    data:
      script: "music_box_next_track"        


- alias: script.music_box_prev_track
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
      key_code: 105       
  action:
  - service: rest_command.ha_script
    data:
      script: "music_box_prev_track"        


- alias: script.music_box_seek_forward_10
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
      key_code: 103       
  action:
  - service: rest_command.ha_script
    data:
      script: "music_box_seek_forward_10"        
                        
                        
- alias: script.music_box_seek_backward_10     
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
      key_code: 108       
  action:
  - service: rest_command.ha_script
    data:
      script: "music_box_seek_backward_10"        
                        
    
    
- alias: script.music_box_set_input_lan     
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
      key_code: 59       
  action:
  - service: rest_command.ha_script
    data:
      script: "music_box_set_input_lan"        
                        


- alias: script.music_box_set_input_toslink     
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
      key_code: 60
  action:
  - service: rest_command.ha_script
    data:
      script: "music_box_set_input_toslink"        
                        

- alias: script.music_box_set_input_usb     
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
      key_code: 61
  action:
  - service: rest_command.ha_script
    data:
      script: "music_box_set_input_usb"        



- alias: script.music_box_play
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
      key_code: 13
  action:
  - service: rest_command.ha_script
    data:
      script: "music_box_play"        
                        


- alias: script.music_box_pause     
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
      key_code: 2
  action:
  - service: rest_command.ha_script
    data:
      script: "music_box_pause"        
                        


- alias: script.music_box_seek_forward_30
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
      key_code: 3
  action:
  - service: rest_command.ha_script
    data:
      script: "music_box_seek_forward_30"        
                        


- alias: script.music_box_seek_backward_30
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
      key_code: 4
  action:
  - service: rest_command.ha_script
    data:
      script: "music_box_seek_backward_30"        
                        


- alias: script.music_box_stop
  trigger:
    platform: event
    event_type: keyboard_remote_command_received
    event_data:
      device_descriptor: "/dev/input/event3"
      key_code: 11
  action:
  - service: rest_command.ha_script
    data:
      script: "music_box_stop"        
                        

    
    